### ISSUE TITLE
Showing installed app in the list?

### ISSUE THREAD

**Issue by HangYang** [HangYang/ext_manager#13]
It did not show installed app before.
Because app wont bother the user. but now it shows app? what do you think?
![image](https://cloud.githubusercontent.com/assets/3389447/23742242/11986526-04e7-11e7-9b7f-d30f3f382a51.png)

**Comment by bfred-it** [comment]
Do you mean that something changed?

I don't have a problem with showing the apps. Maybe we can also color them somehow

**Comment by HangYang** [comment]
Yes, It does not show app before, but now it is showing.
I think put them in the end or hide that would be fine.

**Comment by HangYang** [comment]
what do you think?

**Comment by bfred-it** [comment]
I think we can leave them as it is. Our code hasn't been changed and apparently [`chrome.management.getAll()`](https://developer.chrome.com/extensions/management#method-getAll) has always shown both apps and extensions:

> `chrome.management.getAll(function callback)`
> Returns a list of information about installed extensions and apps.

Both apps and extensions can be disabled the same way for the user, so I think they can be left in there.

**Comment by bfred-it** [comment]
Ah true, I missed [this line](https://github.com/HangYang/ext_manager/blob/3d716d1ec067d8ccef53993d5248d45aa04d1434/popup.js#L28)

For me it's ok to have the apps in there, for the user they can be enabled/disabled the same way from `chrome://extensions`

**Comment by HangYang** [comment]
For  me, most of the extension injects content script to page or has background process, that's why I want to disable/enable them quickly. But app has no this issue, so most of the time I don't care whether an app is enabled or not.

**Comment by bfred-it** [comment]
If you want I can hide them from the list
